# Generated by Django 4.2.15 on 2024-09-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0002_alter_payment_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='identification',
            field=models.CharField(max_length=50, verbose_name='ID card number or passport'),
        ),
    ]
