# Generated by Django 4.2.15 on 2024-09-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0003_alter_customerinfo_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='abbr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='abbreviation of the city'),
        ),
    ]
